import path from "node:path";

import { compactList, dataDir, readJson, shortDate, writeText } from "./lib.mjs";

const configPath = path.join(dataDir, "profile.config.json");
const reposPath = path.join(dataDir, "repos.json");
const outputPath = path.join(path.dirname(dataDir), "README.md");

function renderCapabilityRows(capabilities) {
  return (capabilities ?? []).map((capability) => {
    const tools = (capability.stack ?? []).join(", ");
    return `| ${capability.domain} | ${tools} | ${capability.evidenceEN} |`;
  }).join("\n");
}

function renderFocusLines(items) {
  return (items ?? []).map((item) => `- ${item}`).join("\n");
}

function renderRepoCards(repos) {
  return repos.map((repo) => {
    const title = repo.url ? `[${repo.name}](${repo.url})` : repo.name;
    const stackSignal = compactList([repo.language, ...(repo.topics ?? [])].filter(Boolean), 5) || "Multi-stack";
    const updated = repo.updatedDate || shortDate(repo.updatedAt);

    return [
      `### ${title}`,
      `- **Role:** ${repo.roleTag}`,
      `- **Signal:** ${stackSignal}`,
      `- **Impact:** ${repo.impactNoteEN || "Add a validated impact statement."}`,
      `- **Updated:** ${updated}`
    ].join("\n");
  }).join("\n\n");
}

function renderMissionLogs(items) {
  return (items ?? []).map((mission) => {
    const stack = (mission.stack ?? []).join(", ");
    const linkLine = mission.link ? `- **Reference:** [Project link](${mission.link})` : "- **Reference:** Project details available on request";

    return [
      `#### ${mission.titleEN} (${mission.period})`,
      `- **Stack:** ${stack}`,
      `- **Outcome:** ${mission.impactEN}`,
      linkLine
    ].join("\n");
  }).join("\n\n");
}

function renderTimelineRows(events) {
  return (events ?? []).map((event) => `| ${event.period} | ${event.titleEN} | ${event.organization} |`).join("\n");
}

function renderCertifications(items) {
  return (items ?? []).map((item) => `- **${item.title}** - ${item.issuer}`).join("\n");
}

function renderAssociations(items) {
  return (items ?? []).map((item) => {
    const highlights = (item.highlights ?? []).map((line) => `  - ${line}`).join("\n");
    return `- **${item.name}** (${item.role})\n${highlights}`;
  }).join("\n");
}

function renderLanguageRows(items) {
  return (items ?? []).map((item) => `| ${item.name} | ${item.level} |`).join("\n");
}

function buildReadme(config, repoData) {
  const { profile } = config;
  const repos = (repoData.repos ?? []).filter((repo) => !repo.missing).slice(0, 6);
  const generatedAt = shortDate(repoData.generatedAt);
  const statsUser = profile.username;

  return `<!-- AUTO-GENERATED by profile/scripts/build-readme.mjs -->

<p align="center">
  <picture>
    <source media="(prefers-reduced-motion: reduce)" srcset="./assets/hero-static.svg" />
    <img src="./assets/hero.svg" alt="${profile.displayName} tactical profile hero" width="100%" />
  </picture>
</p>

<p align="center">
  <img src="https://komarev.com/ghpvc/?username=${statsUser}&style=for-the-badge&color=0ea5e9" alt="Profile views" />
  <img src="https://img.shields.io/badge/Focus-DevOps%20%7C%20AI%20Automation-0b1220?style=for-the-badge&logo=githubactions&logoColor=22d3ee" alt="Focus badge" />
  <img src="https://img.shields.io/badge/Location-Tunis%2C%20Tunisia-0b1220?style=for-the-badge&logo=googlemaps&logoColor=22d3ee" alt="Location badge" />
</p>

## Mission Briefing

${config.summary.en}

${renderFocusLines(config.focusNow)}

> "${profile.quote}"

<details>
<summary><strong>Version Francaise</strong></summary>

${config.summary.fr}

${renderFocusLines(config.focusNowFr)}

</details>

<p align="center">
  <img src="./assets/status-strip.svg" alt="Status strip" width="100%" />
</p>

## Capability Matrix

<p align="center">
  <img src="./assets/skills-matrix.svg" alt="Capability matrix" width="100%" />
</p>

| Domain | Stack | Evidence |
| --- | --- | --- |
${renderCapabilityRows(config.capabilities)}

## Featured Mission Logs

${renderRepoCards(repos)}

<details>
<summary><strong>Operational Projects from CV</strong></summary>

${renderMissionLogs(config.missionLogs)}

</details>

## Engineering Timeline

<p align="center">
  <img src="./assets/timeline.svg" alt="Engineering timeline" width="100%" />
</p>

| Period | Milestone | Organization |
| --- | --- | --- |
${renderTimelineRows(config.timeline)}

## Certifications and Leadership

### Certifications
${renderCertifications(config.certifications)}

### Leadership and Communities
${renderAssociations(config.associations)}

### Languages
| Language | Level |
| --- | --- |
${renderLanguageRows(config.languages)}

## GitHub Signal

<p align="center">
  <img height="170" src="https://github-readme-stats.vercel.app/api?username=${statsUser}&show_icons=true&theme=tokyonight&hide_border=true&rank_icon=github" alt="GitHub stats"/>
  <img height="170" src="https://github-readme-stats.vercel.app/api/top-langs/?username=${statsUser}&layout=compact&theme=tokyonight&hide_border=true" alt="Top languages"/>
</p>

## Contact and Opportunities

- **Target:** ${profile.targetRole}
- **LinkedIn:** [${profile.displayName}](${profile.linkedin})
- **Email:** [${profile.email}](mailto:${profile.email})
- **Last profile refresh:** ${generatedAt}

---

<p align="center">
  <strong>Built for internship and job opportunities.</strong><br/>
  Tactical, evidence-first profile narrative with weekly automation.
</p>
`;
}

async function main() {
  const config = await readJson(configPath);
  const repos = await readJson(reposPath);
  const content = buildReadme(config, repos);
  await writeText(outputPath, content);
  console.log("[build-readme] Generated profile/README.md");
}

main().catch((error) => {
  console.error(`[build-readme] ${error.stack || error.message}`);
  process.exit(1);
});
